[settings]
lockfile = true
npm.package_manager = "npm"

[tools]
python = "3.14.5"
uv = "0.11.14"
node = "24.15.0"
powershell-core = "7.6.1"
gh = "2.92.0"
"npm:@openai/codex" = "0.130.0"
yt-dlp = "2026.03.17"
"conda:ffmpeg" = "8.1.1"
"conda:git" = "2.54.0"
