jp:
  character_slug: jp
  display_name: JP
  sources:
    official: https://www.streetfighter.com/6/ja-jp/character/jp/frame
    supercombo_data: https://wiki.supercombo.gg/w/Street_Fighter_6/JP/Data
    supercombo_frame_data: https://wiki.supercombo.gg/w/Street_Fighter_6/JP/Frame_data
